export const CONSTS =
	{
		PROFILE: {
			SET_PROFILE_INFO: 'SET_PROFILE_INFO',
		},
		POSTS: {
			ADD_POST: 'ADD_POST',
			SET_VALUE: 'SET_VALUE',

		},
		DIALOG: {
			SET_NEW_MESSAGE_VALUE: 'SET_NEW_MESSAGE_VALUE',
			SEND_NEW_MESSAGE: 'SEND_NEW_MESSAGE',
		},
		USERS: {
			FOLLOW: 'FOLLOW',
			UNFOLLOW: 'UNFOLLOW',
			SET_USERS: 'SET_USERS',
			SET_PAGE: 'SET_PAGE',
			SET_TOTAL: 'SET_TOTAL',
			SET_LOADING: 'SET_LOADING',
		},
		AUTHORIZATION: {
			SET_LOGIN_DATA: 'SET_LOGIN_DATA'
		}

	};